# Generated by Django 2.0.7 on 2018-07-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotnisko_startu', models.CharField(max_length=100)),
                ('czas_startu', models.DateTimeField()),
                ('lotnisko_ladowania', models.CharField(max_length=100)),
                ('czas_ladowania', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasazer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=42)),
                ('nazwisko', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Samolot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znaki_rejestracyjne', models.CharField(max_length=100)),
                ('liczba_miejsc', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='pasazerowie',
            field=models.ManyToManyField(to='loty.Pasazer'),
        ),
        migrations.AddField(
            model_name='lot',
            name='samolot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loty.Samolot'),
        ),
    ]
